1. __What does one need to do to use a module?__
    
    We need to import the respective module into our code-base by using the import statement.
1. __Name a Module (not the DateTime Nodule) we looked at and write a line or 2 of code as an example using this module.__


In [2]:
import math
print(math.pi)

3.141592653589793


3. __What is a benefit of using Exception handling?__
    
    With this code device we can keep going past many errors.

1. __what are the 4 components used for Python Exception Handling?__
    
    * try
    * except
    * else
    * finally
1. __NumPy arrays are like what Python data type?__

    List

1. __What is one of the main benefits of using NumPy arrays.__

    * Less memory usage.
    * Fast and Convenient.

1. __What is one of the main requirements about the 'dtype' of NumPy arrays?__

    You need to explicitly specify which data type you want.
1. __Of the 10 uses of NumPy, name 2.__

    * Searching, sorting, counting. 

    * Mathematical Operations.

1. __Name one of the other libraries we'll use with NumPy?__
    * Pandas


1. __What is the shape of NumPy arrays?__

    The number of dimesions and items in an array.
1. __What is a Tensor?__

    An array with more than 3 dimensions.
1. __Name a reason why it's better using NumPy for Data Analysis than using a Python List?__

    List stores items that are of various data types, 
    while arrays store only elements of the same data type.

1. __When creating an "empty" array, where do the elements come from?__
    The function empty creates an array whose initial content is random and depends on the state of the memory.


In [8]:
#Use the DateTime module to get Current Date and Time, and save it to a variable. Then extract just the Full month name form that variable.
import datetime as dt

x = dt.datetime.now()

print ("The current month is: ", x.strftime("%B"))

The current month is:  February


In [23]:
# 2)
def info (firstName, dayName = "Sunday"):
    print ("Hi", firstName+"! Happy "+dayName+"!")  

info("Blanche")

info("Timmy", "Monday")

Hi Blanche! Happy Sunday!
Hi Timmy! Happy Monday!


In [46]:
#3

try:     
    print(y)
except:
    print ("An exception has occured")

An exception has occured


In [54]:
#3

try:     
    print("y")
except:
    print ("An exception has occured")

else:
    print("Working")

y
Working


In [55]:

try:
    print(y)
except:
    print("Something went wrong")
finally:
    print("The 'try except' is finished")

Something went wrong
The 'try except' is finished


In [57]:
#4
import numpy as np

array1 = np.arange(12).reshape(2,3,2)

array1


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [59]:
#5
import numpy as np

q5 = np.linspace(0,20, 6)

q5

array([ 0.,  4.,  8., 12., 16., 20.])

In [63]:
#6
import copy

q6 = copy.deepcopy(q5)

print (q6)

[ 0.  4.  8. 12. 16. 20.]


In [66]:
# 'broadcast' the addition of a 1-D array to a 2-D array
from numpy import array, newaxis

arr1= array ([0.71, 0.1, 0.24, 0.3])
arr2= array ([0.8, 0.59, 1.0, 1.11])

print ("The multiplication of array 1 and array 2 is: \n")
print (arr1[:,newaxis]* arr2)



The multiplication of array 1 and array 2 is: 

[[0.568  0.4189 0.71   0.7881]
 [0.08   0.059  0.1    0.111 ]
 [0.192  0.1416 0.24   0.2664]
 [0.24   0.177  0.3    0.333 ]]
