1. **What does Pandas stand for?**

    It is derived from the word "Panel Data"
1. **What are the 2 collections used in Pandas?**

    Series and DataFrames
1. **Name 4 things Pandas can do for us.**

    * Data cleansing
    * Data normalization
    * Data visualization
    * Data inspection
1. **To permanently sort a DataFrame, which keyword should one use with the df.sort() method?**

    values
1. **What is a CSV**

    Comma Separated Values which stores data in a table format.
1. **When cleaning data what values do we not like in our data?**

    Duplicates

In [2]:
#1 Concatenate these 3 arrays into a new array named newArray
import numpy as np
array1= np.array([[25, 16]])
array2= np.array ([[11, 2], [13, 4]])
array3= np.array([[7, 81], [5, 6], [11, 12]])

newArray= np.concatenate((array1, array2, array3))
newArray

array([[25, 16],
       [11,  2],
       [13,  4],
       [ 7, 81],
       [ 5,  6],
       [11, 12]])

In [6]:
#2 Sort 'newArray' in order into 'sortedArray'

sortedArray=np.sort(newArray)
sortedArray

array([[16, 25],
       [ 2, 11],
       [ 4, 13],
       [ 7, 81],
       [ 5,  6],
       [11, 12]])

In [16]:
#3 Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.

reshapedArray = np.reshape(sortedArray,(2,2,3) )
reshapedArray

array([[[16, 25,  2],
        [11,  4, 13]],

       [[ 7, 81,  5],
        [ 6, 11, 12]]])

In [26]:
#4 Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

a , b = reshapedArray

a1 , a2 = a
b1 , b2 = b

print(a1)
print("\n",a2)
print("\n",b1)
print("\n",b2)

[16 25  2]

 [11  4 13]

 [ 7 81  5]

 [ 6 11 12]


In [37]:
# Combined and sort the following arrays into one called 'comboArray' ...
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one,two,three))
comboArray=np.sort(comboArray)
comboArray

array([ 0,  1,  2,  3,  4,  5,  6,  7, 10, 11, 12, 13, 14, 15, 16, 17, 20,
       21, 22, 23, 24, 25, 26, 27])

In [64]:
#6
print(comboArray[1])
print(comboArray[2:])
print(comboArray[3:13])
print(comboArray[-6:])
print(comboArray[0:-8])
print(comboArray[20:])
print(comboArray[::-1][::5])


1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17]
[24 25 26 27]
[27 22 15 10  3]


In [69]:
#7 Using simple math operations, broadcast the addition (+), division (/), and multiplication (*) operations for these 2 arrays -
arraya = ([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])
arrayb = ([[17.0, 70.0, 10.7]])
addition= np.add(arraya, arrayb)
division= np.divide(arraya,arrayb)
multiplication= np.multiply(arraya, arrayb)

print("Addition: \n", addition ,"\n")
print("Division: \n", division, '\n')
print("Multiplication: \n", multiplication, '\n')

Addition: 
 [[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]] 

Division: 
 [[[0.         0.         0.00934579]
  [0.58823529 0.14714286 0.93551402]]

 [[1.17647059 0.286      1.87850467]
  [1.76470588 0.44285714 2.8317757 ]]

 [[2.37647059 0.34285714 3.73831776]
  [0.88235294 0.22142857 2.38317757]]] 

Multiplication: 
 [[[0.00000e+00 0.00000e+00 1.07000e+00]
  [1.70000e+02 7.21000e+02 1.07107e+02]]

 [[3.40000e+02 1.40140e+03 2.15070e+02]
  [5.10000e+02 2.17000e+03 3.24210e+02]]

 [[6.86800e+02 1.68000e+03 4.28000e+02]
  [2.55000e+02 1.08500e+03 2.72850e+02]]] 



In [70]:
#8 Use the NumPy Arithmetic functions to do the subtraction of the above two arrays in pont #7.

Substraction = np.subtract(arraya, arrayb)
print ('Substraction: \n', Substraction)

Substraction: 
 [[[-17.   -70.   -10.6 ]
  [ -7.   -59.7   -0.69]]

 [[  3.   -49.98   9.4 ]
  [ 13.   -39.    19.6 ]]

 [[ 23.4  -46.    29.3 ]
  [ -2.   -54.5   14.8 ]]]


In [80]:
#9
modulo = np.mod(Substraction,3)
modulo

array([[[1.  , 2.  , 1.4 ],
        [2.  , 0.3 , 2.31]],

       [[0.  , 1.02, 0.4 ],
        [1.  , 0.  , 1.6 ]],

       [[2.4 , 2.  , 2.3 ],
        [1.  , 2.5 , 2.8 ]]])

In [113]:
#10
import pandas as pd

ingredients = pd.Series(['Flour','Milk', 'Eggs', 'Spam'], name = 'Ingredients')
quantity = pd.Series([ 4 , 1 , 2 , 1 ], name = 'Quantity')
unit = pd.Series([ 'cups' , 'cup' , 'large' , 'can' ], name = 'Unit')

df = pd.concat([ingredients, quantity, unit], axis=1)

df



Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can

In [115]:
#11
data =     {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }
studentData = pd. DataFrame(data)
studentData

Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

In [119]:
#12 add new collumn to dataframe studentData

deserts= ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

studentData['Deserts'] = deserts
studentData

Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        Deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa

In [123]:
#13 Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

studentData.sort_values(by = ['Name', 'address'], inplace = True)
studentData

Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        Deserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge

In [128]:
#14 Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

df.to_csv('dfhomework5.csv', index=True)
df = pd.read_csv('dfhomework5.csv')
print(df)

  Unnamed: 0  Cows  Goats
0     Year 1    12     22
1     Year 2    20     19


In [152]:
#15(A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, 
#and save a copy with a different name.

#Create data on vegetables

vegetable = pd.Series (['Asparagus', 'Carror', 'Cucumber' , 'Onion'], name="Vegetable")
servingSize = pd.Series (['5 Spears', '1 of 7" long', '1/3 Medium', '1 Medium'], name='Serving size')
potassium = pd.Series ([230 , 250, 140 , 190], name='Potassium mg')
vitamina= pd.Series ([10, 110, 4, 0], name='Vitamin A %DV')
vitaminc= pd.Series ([15, 10, 10, 20], name="Vitamin C %DV")

vegdata= pd.concat ([vegetable, servingSize, potassium,vitamina,vitaminc], axis=1)

#save as csv file
vegdata.to_csv('vegetable.csv', index=False)
vegdata = pd.read_csv('vegetable.csv')
print(vegdata)


   Vegetable  Serving size  Potassium mg  Vitamin A %DV  Vitamin C %DV
0  Asparagus      5 Spears           230             10             15
1     Carror  1 of 7" long           250            110             10
2   Cucumber    1/3 Medium           140              4             10
3      Onion      1 Medium           190              0             20


In [160]:
vegdata2= vegdata
vegdata2.insert(1, "Calories", [20,30,10,45], True)
vegdata2.to_csv('vegetable2.csv', index=False)
vegdata2 = pd.read_csv('vegetable2.csv')
vegdata2

Vegetable  Calories  Calories.1  Serving size  Potassium mg  Vitamin A %DV  \
0  Asparagus        20          20      5 Spears           230             10   
1     Carror        30          30  1 of 7" long           250            110   
2   Cucumber        10          10    1/3 Medium           140              4   
3      Onion        45          45      1 Medium           190              0   

   Vitamin C %DV  
0             15  
1             10  
2             10  
3             20